version: '3'
services:
  ModelHandler:
    image: ollama/ollama
    hostname: ModelHandler
    restart: always
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
  ChatbotMarketing:
    image: elghallali/streamlit-chatbot-rag-marketing
    hostname: ChatbotMarketing
    ports:
      - 8501:8501
    volumes:
      - ./data/chroma:/app/chroma
    depends_on:
      - ModelHandler
